language: java
jdk:
- oraclejdk11
dist: trusty
install: true
branches:
  only:
  - master
  - develop
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-knowledgebase-service
  -Ppublic -q
deploy:
- provider: script
  script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
  skip_cleanup: true
  on:
    branch: develop
addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "GMsHMmjOcFaafCwVde9vRY6m9wfZkqAJW2ETtjmMxAQYTlnt8yA4fo+tgydFBRDNBIWr3vXIlKdQSasM8hr3gm1sTErbXZZUPUf4QbQ8hY8SlwaMHrkCRZZZ18Jo7UuNpwZLVXv6IIkLKm1QXre2fnvFtsLDikzHV0o0GQTfkDRPIxJSLBFmhtmwlRSPPATJt3z4teHH1c3B2OTUDpPrHoziS9a6GX62/UZQs0/H9uHicO1HwNs9onkWfk+yav3Jgz0sFyyR46KPHeWXByxW3DCVkpukcLdOsI4Df44imNZVkm4KDpC/SFU09hFSf2pR4mPTZXmLu5SEOForyoM9e0/Pbr/3dkdF8EUOJ9LJHYAPyCz28WPIE6jG53c6QisrB2ydS23x26LvHPJksZLAQpJYkNFuDO/1sLj14NIXcjUp4TcAk2c0bBN5tJXSkXKI4LbKgYqZVzeSoHpgOix9BS/C7rbHChEkRY7BGub1kfSRKFiBm8YaEbYLoJXc5RZSRTijS5oPQoPsJ4wZzxHDq2Hmmhisyp2oP4FlXPwEcemywyahN/yBvs7holuoeWx4MJDu6FjIMWfXU063IGLEp2idYCWLfGWZAXEoSr4ZVrMuAZzxgQyet7jO9TUca0qIFeugYDtsGERN7eeSCkUmLMLr5AMK6nri6MVhSa7CBQg="
env:
  global:
  - secure: "jzz8097SdmgRVsfT7NpGRK/xM3/XT1BJBnB821j0r3JBju/5cI6VIG7We//nTGeSQj+IpJEyFsAAyNyuP7a/wOdOTBPVMSPzbUdt/pnbd2uyUhjINQ2bYt0aMhLVNS6xOA6Fp3GNegunT+w+EXcTRr4tV7yHYb9x8mZ0tKygd/XKZNN5QQnGZCo0jCmUXAv0wdTyeIv8HfWycDn6fhBDuW31pKzGFoVRAIv9slp4s8jYfp+UDicNrsF6pHkCkaf+67ixMO3v3HNpHTkB6WwnUwfTuYcEd049D8OZ5ODso8V5Gq7rjfH+PG0J33yCoWY0re8P8Ir8FX50KA/YoEy6Z8NnyLssJabA5hhOzsZlhoBC/u+MHfCj+7ewAI5dfeO9ZjPZ4eWnwXxXJilrmx5V53T4fD0lH3Lj8IkBASUEtMCS6Q8aaWAbWF2XCVP/0TNlqDMHZriDjX1FkC+4ti0NCh8mJLupzg1O+fRgXEw1UxERdg8jme65odYnUO0TxFiSeuucUTiKm8Sgu+5IEWTGSU3gF0sjH/OIr1s3fFrRPCdMLFYaOnV8yxEJl2JyhGXCaEazog8u5HmMqNSZIogQ6sCgKURJf/LBb3PeMe0yUs51M5gk3EoIa9J4ueK6jFPYU8HZvQ4AFfUJqG/cPIFOph3ZnSMrxcEKsdUmg2UxrRo="
  - secure: "VqLFYAJ+E6/T/rmdKy3gcTQT9DWKgI/UPcIjLPSAYSOm3C00s0mM1QPRE2Mla1L1chs3nylJBup6JD4Mz8k8d+0zJdQuUsd/KI9R4f0ZwcqHQ8RIgW1yITLxRskdWUte38+bYIoCKRxC0zySooS58jtO92LehVQsLmm8//5MJcu1BPkXrMpOV/sKQ4hjHOSXWWjZEPC3Sxo4eazUNbvM+Awb1rVRG+d0t1bhPkggku3Ipujs47x2nc9l0oVFHwr7q4U6ub/WyOJPBzqSUZhfaQg54l59IKym7ch5RLcO9WwXNesI58DHimJnWHjwmiPbdzk7hP/cFXHa9nEYCfBiWDOEWU9rrnHmIJmIgFSEmyQWMs/ICvDZ26T9H07y2mvxE1C9MZ0HzjLf/EvuoCTYJwYf1+GcDG8k12qytPBfrxOfSzxSOK8/oy/YecA0gHL5uVLs3/bAdQVEt8iS3VHZZ5TJGgKi5L1JUE6G0RKOHJKk6uqSKADblz4uXdXd7ItIjYPorcdYLSGJnJh2GREGBSvJwj/3giHvraqtQRU0T654Zpx0UvGo6sYlek6z67E26gA3bih9m/JunGyVy/o5WYooAPjYq62tx1mLeAkLHVpM8BxEYyvmAvn2hPygYdQbPLjCux6Jz1s/lv1zn3t9eWqv4Fur2niSgJuO14/DNyw="
